# Generated by Django 3.0 on 2019-12-11 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
