# Generated by Django 2.2.8 on 2019-12-19 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('floreria', '0002_auto_20191210_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flor',
            name='estado',
            field=models.TextField(),
        ),
    ]
